name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy
    - name: Run clippy
      run: cargo clippy --profile ci-test && cargo clippy --profile ci-test --example viaduct
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests
      run: cargo test --profile ci-test
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests (bincode)
      run: cargo test --profile ci-test --features bincode
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests (speedy)
      run: cargo test --profile ci-test --features speedy
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test
      run: cargo run --example viaduct --profile ci-test
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test (bincode)
      run: cargo run --example viaduct --profile ci-test --features bincode
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test (speedy)
      run: cargo run --example viaduct --profile ci-test --features speedy
      env:
        RUSTFLAGS: --cfg ci_test

  test_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy
    - name: Run clippy
      run: cargo clippy --profile ci-test && cargo clippy --profile ci-test --example viaduct
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests
      run: cargo test --profile ci-test
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests (bincode)
      run: cargo test --profile ci-test --features bincode
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests (speedy)
      run: cargo test --profile ci-test --features speedy
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test
      run: cargo run --example viaduct --profile ci-test
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test (bincode)
      run: cargo run --example viaduct --profile ci-test --features bincode
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test (speedy)
      run: cargo run --example viaduct --profile ci-test --features speedy
      env:
        RUSTFLAGS: --cfg ci_test

  test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy
    - name: Run clippy
      run: cargo clippy --profile ci-test && cargo clippy --profile ci-test --example viaduct
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests
      run: cargo test --profile ci-test
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests (bincode)
      run: cargo test --profile ci-test --features bincode
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Run doctests (speedy)
      run: cargo test --profile ci-test --features speedy
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test
      run: cargo run --example viaduct --profile ci-test
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test (bincode)
      run: cargo run --example viaduct --profile ci-test --features bincode
      env:
        RUSTFLAGS: --cfg ci_test
    - name: Test (speedy)
      run: cargo run --example viaduct --profile ci-test --features speedy
      env:
        RUSTFLAGS: --cfg ci_test

  fmt_unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check

  fmt_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check